
- name: install maven
  ansible.builtin.dnf:
    name: maven
    state: present

- name: install dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: rename jar file
  ansible.builtin.command: "mv /app/target/{{component}}-{{shipping_version}}.jar /app/{{component}}.jar"
  args:
    chdir: /app             