- name: install mysql client   
  ansible.builtin.dnf: 
    name: mysql
    state: present  # This installs the MySQL client to connect to the MySQL database     

- name: check cities schema exists or not
  ansible.builtin.command: mysql -h mysql.abcompanies.store -uroot -p{{ mysql_password }} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
  register: schema 

- name: print output  
  ansible.builtin.debug:
    msg: "schema output: {{ schema.stdout }}"

- name: load cities data     
  ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -p{{ mysql_password }}  < /app/db/schema.sql"
  when: schema.stdout != "1" 

- name: load master data
  ansible.builtin.shell: "mysql -h  {{MYSQL_HOST}}  -uroot -p{{ mysql_password }}  < /app/db/master-data.sql"

- name: load app user
  ansible.builtin.shell: "mysql -h  {{MYSQL_HOST}}  -uroot -p{{ mysql_password }}  < /app/db/app-user.sql"

  
